<a href="https://colab.research.google.com/github/Swarnalakshmi2223/DATA_SCIENCE/blob/main/100_Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

Exception: ignored

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:


print("NumPy Version:", np.__version__)
print("\nNumPy Configuration:")
np.show_config()

NumPy Version: 1.23.5

NumPy Configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language 

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

my_array = np.zeros(10)
memory_size = my_array.nbytes
print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:

my_vector = np.arange(10, 50)
print(my_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
my_vector = np.array([1, 2, 3, 4, 5])
reversed_vector = my_vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:

my_array = np.arange(9)
my_matrix = my_array.reshape(3, 3)
print(my_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:

my_array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(my_array)
print(non_zero_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:


identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:

random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.47291957 0.7447735  0.02702357]
  [0.37473686 0.97271052 0.85070465]
  [0.39645792 0.197343   0.0761907 ]]

 [[0.18007758 0.66178488 0.41078801]
  [0.50923739 0.85714339 0.83934788]
  [0.56124022 0.32004364 0.93016777]]

 [[0.23221334 0.3340745  0.54781013]
  [0.88499568 0.06496995 0.19161518]
  [0.89799547 0.68236127 0.51932813]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:


random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0014312859588676563
Maximum value: 0.9988959208459914


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:


random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Mean value:", mean_value)

Mean value: 0.5519561234380637


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:

rows, cols = 5, 5
border_array = np.ones((rows, cols))

border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:

existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
rows, cols = existing_array.shape
bordered_array = np.zeros((rows + 2, cols + 2))

bordered_array[1:-1, 1:-1] = existing_array

print(bordered_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:


result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.3 == 3 * 0.1

print("Result 1:", result1)
print("Result 2:", result2)
print("Result 3:", result3)
print("Result 4:", result4)
print("Result 5:", result5)
print("Result 6:", result6)

Result 1: nan
Result 2: False
Result 3: False
Result 4: nan
Result 5: True
Result 6: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:


matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:


checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np

shape = (6, 7, 8)
element_number = 100
index = np.unravel_index(element_number, shape)

print("Index (x, y, z) of the 100th element:", index)

Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
checker_tile = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(checker_tile, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:


random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.mean()) / random_matrix.std()
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.16027193 0.60012484 0.62716907 0.5430988  0.30818566]
 [0.96599674 0.78866321 0.92232636 0.21810847 0.63084869]
 [0.36817333 0.14112722 0.44843924 0.45639604 0.27855584]
 [0.83535773 0.37274827 0.75945905 0.64707387 0.99653171]
 [0.08779762 0.61138488 0.21255952 0.10823866 0.34895329]]

Normalized Matrix:
[[-1.2361261   0.37615917  0.4752901   0.16712967 -0.69394683]
 [ 1.71726635  1.06724848  1.55719211 -1.02412567  0.48877776]
 [-0.47406143 -1.30630123 -0.1798459  -0.15068018 -0.80255522]
 [ 1.23840772 -0.45729195  0.96020035  0.54825132  1.82919256]
 [-1.5017814   0.41743296 -1.0444654  -1.42685457 -0.54451266]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:

color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
example_color = np.array((255, 0, 0, 128), dtype=color_dtype)
print("Example Color (RGBA):", example_color)

Example Color (RGBA): (255, 0, 0, 128)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:

matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
print("Matrix 1 (5x3):")
print(matrix1)
print("\nMatrix 2 (3x2):")
print(matrix2)
print("\nMatrix Product (5x2):")
print(result)

Matrix 1 (5x3):
[[0.99927005 0.1536233  0.99702652]
 [0.55811879 0.97591561 0.12821625]
 [0.79183553 0.35133448 0.53496129]
 [0.742706   0.78273898 0.78153356]
 [0.91597407 0.70702025 0.94813951]]

Matrix 2 (3x2):
[[0.39428391 0.40159124]
 [0.94015309 0.92156721]
 [0.64797829 0.60344661]]

Matrix Product (5x2):
[[1.18447706 1.14452457]
 [1.22064868 1.20087911]
 [0.9891595  0.96459313]
 [1.53514827 1.49122458]
 [1.64023492 1.59156542]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as n
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:

Z = np.array([1, 2, 3, 4, 5])

# Expression 1
print(Z**Z)

# Expression 2
print(2 << Z >> 2)

# Expression 3
print(Z <- Z)

# Expression 4
print(1j*Z)

# Expression 5
print(Z/1/1)

# Expression 6 (Not legal)
# This will result in a syntax error.
# print(Z<Z>Z)

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-3-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-3-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 10.  -6. -10.   7.   8.   2.  -5.  -4.  -6.   5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:

import numpy as np
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

# Your NumPy code here

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result)

False


<ipython-input-18-a61418a4c866>:3: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

# Get today date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Print the results
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-11-20
Today: 2023-11-21
Tomorrow: 2023-11-22


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:


# Assuming A and B are NumPy arrays of the same shape
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
A += B
A = (-A / 2)

# Result is stored in A
print(A)

[-2.5 -3.5 -4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 7. 7. 8. 1. 9. 6. 7. 7. 4.]
[2. 7. 7. 8. 1. 9. 6. 7. 7. 4.]
[2. 7. 7. 8. 1. 9. 6. 7. 7. 4.]
[2 7 7 8 1 9 6 7 7 4]
[2. 7. 7. 8. 1. 9. 6. 7. 7. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0440265  0.13552708 0.16957898 0.32620872 0.3834593  0.38636225
 0.46017806 0.59204269 0.77967815 0.79248971]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
def are_arrays_equal(arr1, arr2):
    # Check if the lengths of the arrays are equal
    if len(arr1) != len(arr2):
        return False

    # Compare each element of the arrays
    for i in range(len(arr1)):
        if arr1[i] != arr2[i]:
            return False

    # If all elements are equal, return True
    return True

# Example usage
array_A = [1, 2, 3, 4, 5]
array_B = [1, 2, 3, 4, 5]

if are_arrays_equal(array_A, array_B):
    print("Arrays are equal")
else:
    print("Arrays are not equal")


Arrays are equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:


# Create a NumPy array and make it read-only
my_array = np.array([1, 2, 3, 4, 5])
my_array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:

# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2) * 10  # Adjust the size or range as needed

# Convert Cartesian coordinates to polar coordinates
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Display the original Cartesian coordinates and the converted polar coordinates
print("Original Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nConverted Polar Coordinates:")
print(np.column_stack((r, theta)))

Original Cartesian Coordinates:
[[0.46476663 4.67051059]
 [0.4318005  8.85471985]
 [2.72689257 8.79293784]
 [8.10854913 1.11439785]
 [8.70617768 7.92564801]
 [6.78456784 0.62558734]
 [2.35361117 9.14124718]
 [4.4589349  6.19578812]
 [4.9322648  5.19766053]
 [3.74930395 0.36198406]]

Converted Polar Coordinates:
[[ 4.69357829  1.47161197]
 [ 8.86524198  1.52206992]
 [ 9.20606859  1.27007841]
 [ 8.18476949  0.1365793 ]
 [11.77342032  0.73850269]
 [ 6.81334869  0.0919474 ]
 [ 9.43937951  1.31879806]
 [ 7.63347175  0.94698936]
 [ 7.16539678  0.81159135]
 [ 3.76673765  0.09624869]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

# Print the original and modified vectors
print("Original vector:", random_vector)


Original vector: [0.3633072  0.         0.75905146 0.57435144 0.02057934 0.8631916
 0.31725492 0.23594897 0.88418655 0.672468  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:

my_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Using a for loop to print each value
for value in my_array:
    print(value)


1
2
3
4
5
6
7
8
9
10


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-9-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


[[0.         0.30451697 0.6309529  0.79570734 0.7756433  0.74584813
  0.5484678  0.8283356  0.75769647 0.29919847]
 [0.30451697 0.         0.49782346 0.58202249 0.53879062 0.44311093
  0.24714537 0.57267686 0.46625279 0.46277025]
 [0.6309529  0.49782346 0.         0.23686458 0.27836734 0.54829059
  0.45977772 0.36096573 0.74247378 0.49138923]
 [0.79570734 0.58202249 0.23686458 0.         0.08168841 0.43028394
  0.43491525 0.14984819 0.65845433 0.7122317 ]
 [0.7756433  0.53879062 0.27836734 0.08168841 0.         0.349044
  0.36801624 0.0827066  0.57846207 0.7238191 ]
 [0.74584813 0.44311093 0.54829059 0.43028394 0.349044   0.
  0.19757422 0.30944422 0.2339081  0.82893614]
 [0.5484678  0.24714537 0.45977772 0.43491525 0.36801624 0.19757422
  0.         0.37307507 0.29575673 0.64517615]
 [0.8283356  0.57267686 0.36096573 0.14984819 0.0827066  0.30944422
  0.37307507 0.         0.54328404 0.79648015]
 [0.75769647 0.46625279 0.74247378 0.65845433 0.57846207 0.2339081
  0.29575673 0.54328404

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-12-8b2485b5e9f4>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


[[ 0.1627942   0.08407155  0.22068873 -0.23302748  0.24390046  0.36933478
  -0.34406924 -0.01282915 -0.48518969 -0.00567416]
 [-0.04489106  0.45014479 -0.18633046  0.07357859 -0.10476885  0.12523659
  -0.00850229 -0.07121627 -0.17965133 -0.0535997 ]
 [ 0.02537758  0.21144476  0.16557234 -0.19961933 -0.07495388  0.39494215
  -0.1147338  -0.21519854 -0.08336088 -0.1094704 ]
 [-0.06369639 -0.3902104  -0.38163496  0.37831783  0.28052741  0.29628076
  -0.17754754 -0.01981762  0.36355974 -0.28577882]
 [ 0.28249785 -0.10870018 -0.28924483  0.31434294 -0.24484374  0.0841744
   0.3563537   0.1917835  -0.27658608 -0.30977756]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[6 1 7]
 [8 1 5]
 [5 1 6]]
[[6 1 7]
 [8 1 5]
 [5 1 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.47911661461585264


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


[6. 5. 4. 1. 4. 2. 3. 3. 1. 1.]
[11.  9.  7.  1.  7.  3.  5.  5.  1.  1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first.
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)


8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


[[68 52 70 47]
 [58 51 48 38]
 [66 41 55 59]]
[[68 52 70 47]
 [58 51 48 38]
 [66 41 55 59]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.48756436 0.60581755 0.57903361 0.65291888 0.41496291 0.46650669
 0.28916783 0.38667408 0.51776017 0.47629959]
0    0.487564
1    0.605818
2    0.579034
3    0.652919
4    0.414963
5    0.466507
6    0.289168
7    0.386674
8    0.517760
9    0.476300
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([1.97908304, 0.44297164, 0.5473677 , 1.67551087, 0.63427027])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 7, 63) ( 7, 84) ( 9, 12) ( 9, 69) (11, 33) (11, 58) (11, 97) (11, 98)
 (12, 69) (14, 63) (14, 99) (21, 58) (21, 74) (24, 76) (24, 94) (28, 58)
 (28, 67) (33, 58) (34, 95) (34, 96) (38, 65) (58, 67) (58, 74) (63, 84)
 (63, 99) (65, 65) (76, 94) (95, 96) (97, 98)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([-0.64475725, -0.38922754, -0.70952899,  0.5049386 , -0.53881173,
        0.94111385,  0.94992496, -0.03169713, -0.33102989,  0.51385067,
        0.52450482, -0.54386889,  0.54544604,  0.93040319, -0.00855548,
       -0.14548637, -0.75178977,  0.34562013, -0.1939461 ,  0.53856606,
        0.53563473, -0.33628067,  0.78097621,  0.30657667, -0.46412724,
        0.90266823,  0.31922377,  0.38625397,  0.22665612, -0.72783543,
        0.2422672 , -0.11265732, -0.53108404,  0.30385378,  0.88929558,
        0.30244721,  0.08379716,  0.46754686,  0.27961624,  0.46307843,
        0.51903787,  0.72608916,  0.81267475, -0.63943755, -0.67005813,
       -0.91096062, -0.04343297, -0.1673698 ,  0.34144892, -0.31733212,
       -0.56362078,  0.55116893,  0.11997125, -0.11656448,  0.86549996,
       -0.21704466, -0.67878572, -0.21234493, -0.1584816 , -0.84768519,
        0.25613194,  0.36817269, -0.22642367, -0.7449779 , -0.89491652,
        0.74059853, -0.57311928,  0.5935068 , -0.99811769, -0.30

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[ 8.64677797  6.59275859  6.77355531  1.64083866 14.01127971  1.95072795
  9.90778358  5.00414043 10.58903022  1.79921824]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 4.8096368   0.07893136 12.30960008  9.75350956  8.52682621  5.59231287
  10.06116702  8.53284548 14.21053176  9.59105354]
 [ 2.63024291  4.60636072  4.38941564  0.89775754  0.29798786  1.22299531
   1.26255001  0.14839149  5.72109119  7.68961158]
 [ 6.98839893  0.60896515 12.95139686 11.49182957 10.34233871  4.80718352
  11.91961648 10.5143087  15.25191077  8.15403897]
 [10.30176506  2.68577044 12.53136414 12.77027568 11.75892081  2.62446273
  13.41475838 12.2426419  15.4070219   5.32825286]
 [ 9.19558727  3.47457094  6.79410591  2.77970709  4.48193383  9.65474115
   3.21038905  5.48353408  6.09411511 18.19062192]
 [ 4.23048259  2.79806271  1.88378353  5.04998778  6.48160321  3.35203541
   5.05166533  6.83395535  1.94591941 11.99229777]
 [ 4.88542848  8.02729687 16.07361209  8.49152143  6.82297631 13.77441487
   8.10336395  5.80897279 16.35070236 19.02235659]
 [ 1.74117533  1.4031461   9.37210759  3.54146868  2.09766932  7.23915998
   3.51248781  1.64759747 10.04814961 13.44933908]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
import numpy as np

def extract_subpart(array, target_element, shape, fill_value=0):
    # Find the indices of the target element
    indices = np.where(array == target_element)

    # Check if the target element is in the array
    if len(indices[0]) == 0:
        print("Target element not found in the array.")
        return None

    # Get the indices of the target element
    target_index = (indices[0][0], indices[1][0])

    # Calculate the start and end indices for the subpart
    start_index = (target_index[0] - shape[0] // 2, target_index[1] - shape[1] // 2)
    end_index = (start_index[0] + shape[0], start_index[1] + shape[1])

    # Pad the array if necessary
    padded_array = np.pad(array, pad_width=((max(0, -start_index[0]), max(0, end_index[0] - array.shape[0])),
                                           (max(0, -start_index[1]), max(0, end_index[1] - array.shape[1]))),
                          mode='constant', constant_values=fill_value)

    # Extract the subpart
    subpart = padded_array[start_index[0]:end_index[0], start_index[1]:end_index[1]]

    return subpart

# Example usage
my_array = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

target_element = 5
subpart_shape = (2, 2)
fill_value = 0

result = extract_subpart(my_array, target_element, subpart_shape, fill_value)
print(result)



[[1 2]
 [4 5]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[4 4 1]
   [0 3 4]
   [3 1 1]]

  [[4 1 3]
   [3 4 4]
   [1 1 3]]

  [[1 3 3]
   [4 4 1]
   [1 3 1]]

  [[3 3 2]
   [4 1 0]
   [3 1 0]]

  [[3 2 2]
   [1 0 0]
   [1 0 4]]

  [[2 2 3]
   [0 0 1]
   [0 4 3]]

  [[2 3 2]
   [0 1 4]
   [4 3 1]]

  [[3 2 0]
   [1 4 3]
   [3 1 3]]]


 [[[0 3 4]
   [3 1 1]
   [0 3 1]]

  [[3 4 4]
   [1 1 3]
   [3 1 0]]

  [[4 4 1]
   [1 3 1]
   [1 0 2]]

  [[4 1 0]
   [3 1 0]
   [0 2 3]]

  [[1 0 0]
   [1 0 4]
   [2 3 3]]

  [[0 0 1]
   [0 4 3]
   [3 3 0]]

  [[0 1 4]
   [4 3 1]
   [3 0 2]]

  [[1 4 3]
   [3 1 3]
   [0 2 0]]]


 [[[3 1 1]
   [0 3 1]
   [1 2 1]]

  [[1 1 3]
   [3 1 0]
   [2 1 0]]

  [[1 3 1]
   [1 0 2]
   [1 0 3]]

  [[3 1 0]
   [0 2 3]
   [0 3 1]]

  [[1 0 4]
   [2 3 3]
   [3 1 3]]

  [[0 4 3]
   [3 3 0]
   [1 3 3]]

  [[4 3 1]
   [3 0 2]
   [3 3 2]]

  [[3 1 3]
   [0 2 0]
   [3 2 2]]]


 [[[0 3 1]
   [1 2 1]
   [0 0 1]]

  [[3 1 0]
   [2 1 0]
   [0 1 0]]

  [[1 0 2]
   [1 0 3]
   [1 0 1]]

  [[0 2 3]
   [0 3 1]
   [0 1 2]]

  [[2 3 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 4  4 11  9  7]
 [ 4  4  2 10  7]
 [11  2  0 42 11]
 [ 9 10 42  1  5]
 [ 7  7 11  5  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:

# Create a large vector Z
Z = np.random.rand(1000000)

# Method 1: Using a loop
result_method1 = np.empty_like(Z)
for i in range(len(Z)):
    result_method1[i] = Z[i] ** 3
print(Z)

[0.91304783 0.51956411 0.7865357  ... 0.12359219 0.42882171 0.75127091]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[1 2 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


[[4 2 3]
 [0 1 4]
 [3 3 3]
 [3 1 3]
 [4 1 0]
 [1 3 4]
 [4 1 0]
 [2 4 2]
 [1 3 0]
 [3 2 2]]
[[4 2 3]
 [0 1 4]
 [3 1 3]
 [4 1 0]
 [1 3 4]
 [4 1 0]
 [2 4 2]
 [1 3 0]
 [3 2 2]]
[[4 2 3]
 [0 1 4]
 [3 1 3]
 [4 1 0]
 [1 3 4]
 [4 1 0]
 [2 4 2]
 [1 3 0]
 [3 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.21170288, 0.03788728, 0.26441621, 0.08297768, 0.12586601,
        0.21766179, 0.06670187, 0.16541623, 0.0092378 , 0.26513533],
       [0.24844035, 0.04446198, 0.31030119, 0.09737706, 0.14770794,
        0.25543332, 0.07827685, 0.19412143, 0.01084087, 0.31114509],
       [0.17994493, 0.03220374, 0.22475063, 0.07053004, 0.10698461,
        0.18500993, 0.05669579, 0.14060183, 0.00785202, 0.22536187],
       [0.50673486, 0.09068751, 0.6329102 , 0.19861649, 0.30127458,
        0.52099818, 0.15965849, 0.39594252, 0.02211173, 0.63463148],
       [0.50593185, 0.0905438 , 0.63190724, 0.19830175, 0.30079716,
        0.52017256, 0.15940548, 0.39531508, 0.02207669, 0.6336258 ],
       [0.27110806, 0.0485187 , 0.33861309, 0.10626175, 0.16118482,
        0.27873908, 0.08541884, 0.21183309, 0.01182999, 0.339534  ],
       [0.4742149 , 0.08486759, 0.59229287, 0.18587018, 0.28194013,
        0.48756286, 0.14941232, 0.37053271, 0.0206927 , 0.59390369],
       [0.63687267, 0.11397754, 0.7954519

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.22895389  0.1214776 ]
